apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TerraformMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-terraform
    app.kubernetes.io/managed-by: kustomize
  name: terraformmachinetemplate-sample
spec:
  template:
    spec:
      source:
        image: ghcr.io/example/machine-module:v0.1.0
      identityRef:
        name: terraformclusteridentity-sample
