/*
Copyright 2026 The CAPTF Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// longDoc is a package comment long enough to count as an overview.
var longDoc = "// Package p " + strings.Repeat("documents itself at length. ", 20) + "\npackage p\n"

// write creates files (path relative to a new temporary directory mapped to
// content) for t and returns that directory.
func write(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

// messages returns the finding messages of Check over dir for t.
func messages(t *testing.T, dir string) []string {
	t.Helper()
	findings, err := Check(dir)
	if err != nil {
		t.Fatalf("Check: %v", err)
	}
	var out []string
	for _, f := range findings {
		out = append(out, f.Msg)
	}
	return out
}

// TestCleanPackage: a fully documented package has no finding.
func TestCleanPackage(t *testing.T) {
	t.Parallel()
	dir := write(t, map[string]string{
		"doc.go": longDoc,
		"a.go": `package p

// T is a thing.
type T struct{}

// Get returns the thing named name.
func Get(name string) T { return T{} }

// Doer does work.
type Doer interface {
	// Do does it to x and reports whether it worked.
	Do(x int) bool
}

// Limit caps things.
const Limit = 3

var _ = Limit // a blank var is exempt
`,
		"a_test.go": `package p

import "testing"

// TestGet checks Get.
func TestGet(t *testing.T) {}
`,
	})
	if got := messages(t, dir); len(got) != 0 {
		t.Errorf("findings = %v, want none", got)
	}
}

// TestGaps: every rule reports its gap.
func TestGaps(t *testing.T) {
	t.Parallel()
	dir := write(t, map[string]string{
		"doc.go": "// Package p is short.\npackage p\n",
		"a.go": `package p

type Undocumented struct{}

// wrong start.
func Named() {}

// Sum adds.
func Sum(a, b int) int { return a + b }

// I is an interface.
type I interface {
	M(x int)
}

const Loose = 1
`,
		"sub/b.go": "package sub\n\n// F is fine.\nfunc F() {}\n",
	})
	got := strings.Join(messages(t, dir), "\n")
	for _, want := range []string{
		"type Undocumented has no doc comment",
		`func Named: the doc comment does not start with "Named"`,
		"func Sum: parameter a is not documented",
		"func Sum: parameter b is not documented",
		"func Sum: the return value is not documented",
		"method I.M has no doc comment",
		"const Loose has no doc comment",
		"the doc.go package comment is",
		"package sub",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("findings lack %q:\n%s", want, got)
		}
	}
}

// TestSkips: generated files, the pinned tools and external test packages
// are not checked.
func TestSkips(t *testing.T) {
	t.Parallel()
	dir := write(t, map[string]string{
		"doc.go":               longDoc,
		"gen.go":               "// Code generated by x. DO NOT EDIT.\n\npackage p\n\nfunc Bare() {}\n",
		"zz_generated.deep.go": "package p\n\nfunc Deep() {}\n",
		"hack/tools/tool.go":   "package tool\n\nfunc Bare() {}\n",
		"x_test.go":            "package p_test\n\nimport \"testing\"\n\n// TestX is documented.\nfunc TestX(t *testing.T) {}\n",
		".hidden/secret.go":    "package h\n\nfunc Bare() {}\n",
		"a.go":                 "package p\n\n// Fine is fine.\nfunc Fine() {}\n",
	})
	if got := messages(t, dir); len(got) != 0 {
		t.Errorf("findings = %v, want none", got)
	}
}

// TestRunExitCodes: run returns 0 on a clean tree, 1 with findings and 2
// when the tree cannot be read.
func TestRunExitCodes(t *testing.T) {
	t.Parallel()
	var out bytes.Buffer
	if code := run(write(t, map[string]string{"doc.go": longDoc}), &out); code != 0 {
		t.Errorf("clean: exit %d: %s", code, out.String())
	}
	if code := run(write(t, map[string]string{"doc.go": longDoc, "a.go": "package p\n\nfunc Bare() {}\n"}), &out); code != 1 {
		t.Errorf("findings: exit %d", code)
	}
	if code := run(filepath.Join(t.TempDir(), "missing"), &out); code != 2 {
		t.Errorf("missing dir: exit %d", code)
	}
}
